### ISSUE TITLE
Database Tooling Idea

### ISSUE THREAD

**Issue by chris-mcc** [petergeneric/stdlib#14]
Off the back of the Hibernate create restriction improvement I'd like to propose we take it further.

I'd actually be a fan of going a step further and disallowing hibernate to create or update the database at all - it's not great at all.

But for that to work out we'd need tooling to separate that process out so that proper tools like Liquibase get called in a controlled, explicit manner.

Perhaps a long term goal could be to integrate with the Tomcat control scripts? E.g. optionally force a DB verify before launching Tomcat or test running DB migration steps.

**Comment by petergeneric** [comment]
See also @bmcleodcd  #13 

That would be ideal, it'd be great if we could:
 - Have an easy way to auto-generate liquibase migrations based on git commits (I wonder if we'd need to be db-specific here or if we could use hsqldb to generate a base DB from the current migrations and have liquibase guess the changes to apply based on the hibernate entities. This might be a bit too ambitious (and may have problems if using SQL Server or Postgres-specific behaviours - although having a way to point the migration scripts at a db specifically for migration generation, create a new schema and then drop the schema afterwards might be a reasonable approach here)
 - Have a way to hook liquibase in so that liquibase has to validate the db state before the application can get a JDBC connection
 - If hibernate and liquibase are both enabled, perhaps we should have hibernate hbm2ddl validate in unit tests so we can check the liquibase migrations are up-to-date with the java entities?

**Comment by chris-mcc** [comment]
Just a few things I'd like to highlight:

1. I'd be wary of relying on hbm2dll validate; I have found it to be quite strict and wouldn't be surprised if it created false positives.

2.  Running Liquibase before hibernate should work well; I've used Liquibase in Springified unit tests to great effect. I do like the idea of Liquibase running before the App even starts, but that could restrict our options for reporting what went wrong.    

3. I'm not sure about the auto-generated liquibase migrations feature idea.  I'd prefer to tackle a migration like so:
1. Take a copy of the DB to be migrated.
2. Checkout required version from Git.
3. Run Liquibase on DB copy.
4.  Run baseline tests on DB Copy.
5. Success? squirrel away a copy of the current DB.
6. Migrate the 'Live' DB.

I think if we could automate steps 1 - 3,5,6 then we'd be good.  I might have something for step 4...

**Comment by petergeneric** [comment]
This was implemented on the 7th of May 2015 as part of c0ef3af05bebe7270609d58366636e8d7c6e106f  - liquibase is now the recommended route for managing database schemas in applications. If liquibase is managing the schema then hibernate is prohibited from modifying the schema.
